version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - type: deploy
        name: "Publish to npm"
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo "Publishing latest release"
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
            yarn semantic-release || exit 0
          else
            echo "Skipping publication in non-release branch"
          fi
