version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:latest"
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install
          command: yarn
      - run:
          name: test
          command: yarn test
      - type: deploy
        name: release
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo "Publishing latest release"
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
            yarn semantic-release || true
          else
            echo "Skipping publication in non-release branch"
          fi
